name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run typecheck
      - name: Test
        run: npm test
      - name: Build (prod + pages)
        run: npm run build:pages
      - name: Record build hash
        run: |
          sha256sum dist/assets/index-*.js | awk '{print $1}' > dist/build-sha.txt || true
          echo "Build JS hash:" && cat dist/build-sha.txt || true
      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist-build
          path: dist
          if-no-files-found: warn

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: production
      url: https://fialucci.github.io/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      # We rely on predeploy hook to rebuild; no need to download artifact
      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Deploy via gh-pages script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
      - name: Verify gh-pages branch
        run: |
          git fetch origin gh-pages --depth=5 || true
          echo "Recent gh-pages commits:" && git log --oneline -n 3 origin/gh-pages || echo "No gh-pages commits yet"
          echo "Published files (remote tree):" && git ls-tree --name-only -r origin/gh-pages | head -n 50 || true
      - name: Guidance
        run: |
          echo "If site not updated:" && echo "1. Check Pages settings -> Source: gh-pages / root" && echo "2. Wait 1-2 minutes & hard refresh" && echo "3. Confirm commit above matches latest gh-pages"
